[package]
name = "factorio_save_upgrader"
version = "0.1.0"
authors = ["mulark <mulark11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "*"
directories = "*"
glob = "*"
lazy_static = "*"
